#!/bin/bash

# This is an old file
# Need to install deps by cat PKGBUILD:depends
# Need to handle raw content

repo='https://github.com/sirius-2/aurin.git'

c_dir="$(pwd)"
mirror_url='hub.fastgit.xyz'
mirror_raw_url='raw.staticdn.net'

tmp_dir=/tmp

handle(){
    baseurl=$(echo $1 | awk -F '/' '{print $3}')
    name=$(echo $1 | awk -F '/' '{print $4}' | awk -F '.' '{print $1}')

    workdir=${tmp_dir}/${name}

    if [[ ${baseurl} == 'aur.archlinux.org' ]];then
        if [[ ! -d ${workdir} ]];then
            git clone $1 $workdir
        fi
        if [[ "$(ls ${workdir})" == "" ]];then sudo rm -rf ${workdir};echo '[ - ] No AUR Package found';exit 1;fi

        cd ${workdir}
        if [[ -f PKGBUILD ]];then

            # depends
            alldepends=($(sed -n '/depends=/,/)/p' PKGBUILD | sed 's/makedepends=(//g' | sed 's/depends=(//g' | sed 's/)//g' | sed 's/"//g' | sed "s/'//g" | sed ":a;N;s/\n//g;ta" | sed 's/ \+/ /g'))
            echo "alldepends: ${#alldepends[@]} : ${alldepends[@]}"
            #eval "sudo pacman -Sy ${alldepends[@]}"

            #sudo pacman -Sy --noconfirm ${alldepends[@]}
            sudo pacman -Sy
            for d in "${alldepends[@]}"
            do
                yes | sudo pacman -S $d
                if [[ $? != 0 ]];then yay -S $d;fi
            done

            sed -i "s/github.com/${mirror_url}/g" PKGBUILD
            sed -i "s/raw.githubusercontent.com/${mirror_raw_url}/g" PKGBUILD
            makepkg
            if [[ $? != 0 ]];then echo '[ - ] Found unhandled issue';exit 1;fi
            sudo pacman -U *.pkg.tar.*
        else
            echo '[ - ] No PKGBUILD found'
            cd ${c_dir}
            exit 1
        fi
        sudo rm -rf ${workdir}
    else
        echo '[ - ] No AUR Package found'
    fi
}

aurinbin(){
    biinname=$(echo $0 | awk -F '/' '{print $2}')
    if [[ $USER == 'root' ]];then
        binpath='/usr/local/bin'
    else
        binpath="$HOME/.local/bin"
        if [[ ! -d ${binpath} ]];then mkdir -p ${binpath};fi
    fi

    case $1 in
        u | update)
            filepath=${tmp_dir}/aurin/aurin
            git clone ${repo} ${tmp_dir}/aurin
            ;;
        *)
            filepath=$(pwd)/${biinname}
    esac
    if [[ -f ${filepath} ]];then sudo cp -f ${filepath} ${binpath}/${biinname};sudo chmod +x ${binpath}/${biinname};fi
    sudo rm -rf ${tmp_dir}/aurin
    echo '[ + ] aleady in PATH'
}

case $1 in
    -i | --install)
        handle $2
        ;;
    -m | --mirror)
        mirror_url=$2
        if [[ "$(echo $3 | awk -F '.' '{print $1}')" == 'raw' ]];then
            mirror_raw_url=$3
            handle $4
        else
            handle $3
        fi
        ;;
    -d | --default)
        mirror_url='github.com'
        mirror_raw_url='raw.githubusercontent.com'
        handle $2
        ;;
    -p | --package)
        handle "https://aur.archlinux.org/${2}.git"
        ;;
    -b | --bin)
        case $1 in
            u | update)
                aurinbin u
                ;;
            *)
                aurinbin
        esac
        ;;
    -h | --help)

cat<<EOF

aurin [arg]

arg:
    -i | --install    install through buildin mirror
    -m | --mirror     custom aur domain
                            eg.
                            aurin -m githubmirror.xx aur_git_url
                            aurin -m githubmirror.xx raw.xxxxx.xx[optional] aur_git_url
    -d | --default    default github domain
    -p | --package    use simple package name eg. yay
    -b | --bin        copy this file to PATH
                            eg. update:
                            aurin -b u
    -h | --help       show help
EOF
        ;;
    *)
        handle $1
esac
